function games() {
  return [
    { name: '10 minutes till dawn', link: '/0 - 100/10-minutes-till-dawn_new.html' },
    { name: '11 11', link: '/0 - 100/11-11_new.html' },
    { name: '12 minibattles', link: '/0 - 100/12-minibattles_new.html' },
    { name: '2048 multitask', link: '/0 - 100/2048-multitask_new.html' },
    { name: '2048', link: '/0 - 100/2048_new.html' },
    { name: '3d car simulator', link: '/0 - 100/3d-car-simulator_new.html' },
    { name: '3d moto simulator 2', link: '/0 - 100/3d-moto-simulator-2_new.html' },
    { name: '4th and goal 2022', link: '/0 - 100/4th-and-goal-2022_new.html' },
    { name: '4x4 drive offroad', link: '/0 - 100/4x4-drive-offroad_new.html' },
    { name: '8 ball pool', link: '/0 - 100/8-ball-pool_new.html' },
    { name: 'a dance of fire and ice', link: '/0 - 100/a-dance-of-fire-and-ice_new.html' },
    { name: 'a small world cup', link: '/0 - 100/a-small-world-cup_new.html' },
    { name: 'adventure drivers', link: '/0 - 100/adventure-drivers_new.html' },
    { name: 'age of war', link: '/0 - 100/age-of-war_new.html' },
    { name: 'air hockey championship deluxe', link: '/0 - 100/air-hockey-championship-deluxe_new.html' },
    { name: 'among us', link: '/0 - 100/among-us_new.html' },
    { name: 'ape sling', link: '/0 - 100/ape-sling_new.html' },
    { name: 'aqua thrills', link: '/0 - 100/aqua-thrills_new.html' },
    { name: 'archery world tour', link: '/0 - 100/archery-world-tour_new.html' },
    { name: 'arithmetica', link: '/0 - 100/arithmetica_new.html' },
    { name: 'athletics hero', link: '/0 - 100/athletics-hero_new.html' },
    { name: 'awesome tanks 2', link: '/0 - 100/awesome-tanks-2_new.html' },
    { name: 'awesome tanks', link: '/0 - 100/awesome-tanks_new.html' },
    { name: 'b cubed', link: '/0 - 100/b-cubed_new.html' },
    { name: 'basket and ball', link: '/0 - 100/basket-and-ball_new.html' },
    { name: 'basket bros', link: '/0 - 100/basket-bros_new.html' },
    { name: 'basket champs', link: '/0 - 100/basket-champs_new.html' },
    { name: 'basket random', link: '/0 - 100/basket-random_new.html' },
    { name: 'basket swooshes', link: '/0 - 100/basket-swooshes_new.html' },
    { name: 'basketball legends', link: '/0 - 100/basketball-legends_new.html' },
    { name: 'basketball line', link: '/0 - 100/basketball-line_new.html' },
    { name: 'basketball stars', link: '/0 - 100/basketball-stars_new.html' },
    { name: 'battle wheels', link: '/0 - 100/battle-wheels_new.html' },
    { name: 'bearsus', link: '/0 - 100/bearsus_new.html' },
    { name: 'big shot boxing', link: '/0 - 100/big-shot-boxing_new.html' },
    { name: 'big tall small', link: '/0 - 100/big-tall-small_new.html' },
    { name: 'bike trials offroad 1', link: '/0 - 100/bike-trials-offroad-1_new.html' },
    { name: 'bike trials winter 1', link: '/0 - 100/bike-trials-winter-1_new.html' },
    { name: 'bike trials winter 2', link: '/0 - 100/bike-trials-winter-2_new.html' },
    { name: 'bitlife', link: '/0 - 100/bitlife_new.html' },
    { name: 'block the pig', link: '/0 - 100/block-the-pig_new.html' },
    { name: 'blocky cars', link: '/0 - 100/blocky-cars_new.html' },
    { name: 'blocky trials', link: '/0 - 100/blocky-trials_new.html' },
    { name: 'bloons tower defense 1', link: '/0 - 100/bloons-tower-defense-1_new.html' },
    { name: 'bloxorz', link: '/0 - 100/bloxorz_new.html' },
    { name: 'blumgi ball', link: '/0 - 100/blumgi-ball_new.html' },
    { name: 'blumgi castle', link: '/0 - 100/blumgi-castle_new.html' },
    { name: 'blumgi rocket', link: '/0 - 100/blumgi-rocket_new.html' },
    { name: 'blumgi slime', link: '/0 - 100/blumgi-slime_new.html' },
    { name: 'bob the robber 4', link: '/0 - 100/bob-the-robber-4_new.html' },
    { name: 'bomb it 7', link: '/0 - 100/bomb-it-7_new.html' },
    { name: 'bowling stars', link: '/0 - 100/bowling-stars_new.html' },
    { name: 'boxing physics 2', link: '/0 - 100/boxing-physics-2_new.html' },
    { name: 'boxing random', link: '/0 - 100/boxing-random_new.html' },
    { name: 'brain for monster truck', link: '/0 - 100/brain-for-monster-truck_new.html' },
    { name: 'brain test 2 tricky stories', link: '/0 - 100/brain-test-2-tricky-stories_new.html' },
    { name: 'brain test 3 tricky quests', link: '/0 - 100/brain-test-3-tricky-quests_new.html' },
    { name: 'brain test tricky puzzles', link: '/0 - 100/brain-test-tricky-puzzles_new.html' },
    { name: 'breaking the bank', link: '/0 - 100/breaking-the-bank_new.html' },
    { name: 'bubble shooter', link: '/0 - 100/bubble-shooter_new.html' },
    { name: 'bubble trouble 3', link: '/0 - 100/bubble-trouble-3_new.html' },
    { name: 'bubble trouble', link: '/0 - 100/bubble-trouble_new.html' },
    { name: 'bullet force', link: '/0 - 100/bullet-force_new.html' },
    { name: 'bumper cars soccer', link: '/0 - 100/bumper-cars-soccer_new.html' },
    { name: 'bunny hop', link: '/0 - 100/bunny-hop_new.html' },
    { name: 'burger bounty', link: '/0 - 100/burger-bounty_new.html' },
    { name: 'burnin rubber 5 xs', link: '/0 - 100/burnin-rubber-5-xs_new.html' },
    { name: 'burnin rubber crash n burn', link: '/0 - 100/burnin-rubber-crash-n-burn_new.html' },
    { name: 'burnout drift seaport max', link: '/0 - 100/burnout-drift-seaport-max_new.html' },
    { name: 'burrito bison', link: '/0 - 100/burrito-bison_new.html' },
    { name: 'candy jump', link: '/0 - 100/candy-jump_new.html' },
    { name: 'cannon strike', link: '/0 - 100/cannon-strike_new.html' },
    { name: 'car climb racing', link: '/0 - 100/car-climb-racing_new.html' },
    { name: 'car rush', link: '/0 - 100/car-rush_new.html' },
    { name: 'cars thief tank edition', link: '/0 - 100/cars-thief-tank-edition_new.html' },
    { name: 'cars thief', link: '/0 - 100/cars-thief_new.html' },
    { name: 'cat gunner super zombie shoot', link: '/0 - 100/cat-gunner-super-zombie-shoot_new.html' },
    { name: 'cat trap', link: '/0 - 100/cat-trap_new.html' },
    { name: 'cats', link: '/0 - 100/cats_new.html' },
    { name: 'chicken merge', link: '/0 - 100/chicken-merge_new.html' },
    { name: 'chrome dino', link: '/0 - 100/chrome-dino_new.html' },
    { name: 'city bike stunt 2', link: '/0 - 100/city-bike-stunt-2_new.html' },
    { name: 'city car driving stunt master', link: '/0 - 100/city-car-driving-stunt-master_new.html' },
    { name: 'city rider', link: '/0 - 100/city-rider_new.html' },
    { name: 'cluster rush', link: '/0 - 100/cluster-rush_new.html' },
    { name: 'coffee shop', link: '/0 - 100/coffee-shop_new.html' },
    { name: 'color switch', link: '/0 - 100/color-switch_new.html' },
    { name: 'color tunnel 2', link: '/0 - 100/color-tunnel-2_new.html' },
    { name: 'cookie clicker', link: '/0 - 100/cookie-clicker_new.html' },
    { name: 'crazy cars', link: '/0 - 100/crazy-cars_new.html' },
    { name: 'crazy tunnel 3d', link: '/0 - 100/crazy-tunnel-3d_new.html' },
    { name: 'cricket world cup', link: '/0 - 100/cricket-world-cup_new.html' },
    { name: 'crossy road', link: '/0 - 100/crossy-road_new.html' },
    { name: 'cubes king', link: '/0 - 100/cubes-king_new.html' },
    { name: 'cubito mayhem', link: '/0 - 100/cubito-mayhem_new.html' },
    { name: 'curve ball 3d', link: '/0 - 100/curve-ball-3d_new.html' },
    { name: 'cyber cars punk racing', link: '/0 - 100/cyber-cars-punk-racing_new.html' },
    { name: 'death chase', link: '/0 - 100/death-chase_new.html' },
    { name: 'death run 3d', link: '/0 - 100/death-run-3d_new.html' },

    { name: 'deepest sword', link: '/100 - 2000/deepest-sword_new.html' },
    { name: 'deer simulator', link: '/100 - 2000/deer-simulator_new.html' },
    { name: 'demolition derby crash racing', link: '/100 - 2000/demolition-derby-crash-racing_new.html' },
    { name: 'detective loupe puzzle', link: '/100 - 2000/detective-loupe-puzzle_new.html' },
    { name: 'dinosaur game', link: '/100 - 2000/dinosaur-game_new.html' },
    { name: 'dog simulator 3d', link: '/100 - 2000/dog-simulator-3d_new.html' },
    { name: 'doge miner', link: '/100 - 2000/doge-miner_new.html' },
    { name: 'doodle champion island', link: '/100 - 2000/doodle-champion-island_new.html' },
    { name: 'doodle jump', link: '/100 - 2000/doodle-jump_new.html' },
    { name: 'draw the hill', link: '/100 - 2000/draw-the-hill_new.html' },
    { name: 'dreadhead parkour', link: '/100 - 2000/dreadhead-parkour_new.html' },
    { name: 'drift boss', link: '/100 - 2000/drift-boss_new.html' },
    { name: 'drift hunters', link: '/100 - 2000/drift-hunters_new.html' },
    { name: 'drive mad', link: '/100 - 2000/drive-mad_new.html' },
    { name: 'drunken duel', link: '/100 - 2000/drunken-duel_new.html' },
    { name: 'duck life 2 world champion', link: '/100 - 2000/duck-life-2-world-champion_new.html' },
    { name: 'duck life 3 evolution', link: '/100 - 2000/duck-life-3-evolution_new.html' },
    { name: 'duck life 4', link: '/100 - 2000/duck-life-4_new.html' },
    { name: 'duck life', link: '/100 - 2000/duck-life_new.html' },
    { name: 'dunkbrush', link: '/100 - 2000/dunkbrush_new.html' },
    { name: 'dunkers', link: '/100 - 2000/dunkers_new.html' },
    { name: 'earn to die', link: '/100 - 2000/earn-to-die_new.html' },
    { name: 'eggy car', link: '/100 - 2000/eggy-car_new.html' },
    { name: 'elastic man', link: '/100 - 2000/elastic-man_new.html' },
    { name: 'electron dash', link: '/100 - 2000/electron-dash_new.html' },
    { name: 'eliza mall mania', link: '/100 - 2000/eliza-mall-mania_new.html' },
    { name: 'energy', link: '/100 - 2000/energy_new.html' },
    { name: 'escaping the prison', link: '/100 - 2000/escaping-the-prison_new.html' },
    { name: 'eugenes life', link: '/100 - 2000/eugenes-life_new.html' },
    { name: 'evo city driving', link: '/100 - 2000/evo-city-driving_new.html' },
    { name: 'extreme car driving simulator', link: '/100 - 2000/extreme-car-driving-simulator_new.html' },
    { name: 'extreme car parking', link: '/100 - 2000/extreme-car-parking_new.html' },
    { name: 'factory balls forever', link: '/100 - 2000/factory-balls-forever_new.html' },
    { name: 'fairy dressup', link: '/100 - 2000/fairy-dressup_new.html' },
    { name: 'fancy pants 2', link: '/100 - 2000/fancy-pants-2_new.html' },
    { name: 'fancy pants 3', link: '/100 - 2000/fancy-pants-3_new.html' },
    { name: 'fancy pants', link: '/100 - 2000/fancy-pants_new.html' },
    { name: 'five nights at freddys 2', link: '/100 - 2000/five-nights-at-freddys-2_new.html' },
    { name: 'five nights at freddys 3', link: '/100 - 2000/five-nights-at-freddys-3_new.html' },
    { name: 'five nights at freddys', link: '/100 - 2000/five-nights-at-freddys_new.html' },
    { name: 'flappy bird origin', link: '/100 - 2000/flappy-bird-origin_new.html' },
    { name: 'flappy bird', link: '/100 - 2000/flappy-bird_new.html' },
    { name: 'fleeing the complex', link: '/100 - 2000/fleeing-the-complex_new.html' },
    { name: 'flying car simulator', link: '/100 - 2000/flying-car-simulator_new.html' },
    { name: 'foot chinko', link: '/100 - 2000/foot-chinko_new.html' },
    { name: 'football legends', link: '/100 - 2000/football-legends_new.html' },
    { name: 'football masters', link: '/100 - 2000/football-masters_new.html' },
    { name: 'fortz', link: '/100 - 2000/fortz_new.html' },
    { name: 'free kick shooter', link: '/100 - 2000/free-kick-shooter_new.html' },
    { name: 'free the key', link: '/100 - 2000/free-the-key_new.html' },
    { name: 'funny shooter 2', link: '/100 - 2000/funny-shooter-2_new.html' },
    { name: 'furious racing 3d', link: '/100 - 2000/furious-racing-3d_new.html' },
    { name: 'g switch 3', link: '/100 - 2000/g-switch-3_new.html' },
    { name: 'geometry dash', link: '/100 - 2000/geometry-dash_new.html' },
    { name: 'getaway shootout', link: '/100 - 2000/getaway-shootout_new.html' },
    { name: 'go kart go ultra', link: '/100 - 2000/go-kart-go-ultra_new.html' },
    { name: 'gobble', link: '/100 - 2000/gobble_new.html' },
    { name: 'gold digger frvr', link: '/100 - 2000/gold-digger-frvr_new.html' },
    { name: 'golf champions', link: '/100 - 2000/golf-champions_new.html' },
    { name: 'golfinity', link: '/100 - 2000/golfinity_new.html' },
    { name: 'google feud', link: '/100 - 2000/google-feud_new.html' },
    { name: 'google snake', link: '/100 - 2000/google-snake_new.html' },
    { name: 'grand prix hero', link: '/100 - 2000/grand-prix-hero_new.html' },
    { name: 'gravity soccer', link: '/100 - 2000/gravity-soccer_new.html' },
    { name: 'grindcraft remastered', link: '/100 - 2000/grindcraft-remastered_new.html' },
    { name: 'grindcraft', link: '/100 - 2000/grindcraft_new.html' },
    { name: 'gun mayhem 2', link: '/100 - 2000/gun-mayhem-2_new.html' },
    { name: 'gun mayhem 3', link: '/100 - 2000/gun-mayhem-3_new.html' },
    { name: 'gun mayhem', link: '/100 - 2000/gun-mayhem_new.html' },
    { name: 'gunspin', link: '/100 - 2000/gunspin_new.html' },
    { name: 'hammer 2 reloaded', link: '/100 - 2000/hammer-2-reloaded_new.html' },
    { name: 'happy room', link: '/100 - 2000/happy-room_new.html' },
    { name: 'head soccer 2023', link: '/100 - 2000/head-soccer-2023_new.html' },
    { name: 'heads arena soccer all stars', link: '/100 - 2000/heads-arena-soccer-all-stars_new.html' },
    { name: 'heart star html5', link: '/100 - 2000/heart-star-html5_new.html' },
    { name: 'hextris', link: '/100 - 2000/hextris_new.html' },
    { name: 'highway racer 3d', link: '/100 - 2000/highway-racer-3d_new.html' },
    { name: 'highway rider extreme', link: '/100 - 2000/highway-rider-extreme_new.html' },
    { name: 'highway traffic', link: '/100 - 2000/highway-traffic_new.html' },
    { name: 'horse shoeing', link: '/100 - 2000/horse-shoeing_new.html' },
    { name: 'horse simulator 3d', link: '/100 - 2000/horse-simulator-3d_new.html' },
    { name: 'house of hazards', link: '/100 - 2000/house-of-hazards_new.html' },
    { name: 'hover racer drive', link: '/100 - 2000/hover-racer-drive_new.html' },
    { name: 'hover racer', link: '/100 - 2000/hover-racer_new.html' },
    { name: 'icy purple head 3', link: '/100 - 2000/icy-purple-head-3_new.html' },
    { name: 'idle ants', link: '/100 - 2000/idle-ants_new.html' },
    { name: 'idle breakout', link: '/100 - 2000/idle-breakout_new.html' },
    { name: 'idle digging tycoon', link: '/100 - 2000/idle-digging-tycoon_new.html' },
    { name: 'idle lumber inc', link: '/100 - 2000/idle-lumber-inc_new.html' },
    { name: 'idle miner', link: '/100 - 2000/idle-miner_new.html' },
    { name: 'idle mining empire', link: '/100 - 2000/idle-mining-empire_new.html' },
    { name: 'idle startup tycoon', link: '/100 - 2000/idle-startup-tycoon_new.html' },
    { name: 'impossible monster truck race', link: '/100 - 2000/impossible-monster-truck-race_new.html' },
    { name: 'impossible tic tac toe', link: '/100 - 2000/impossible-tic-tac-toe_new.html' },
    { name: 'infinity loop', link: '/100 - 2000/infinity-loop_new.html' },
    { name: 'iron snout', link: '/100 - 2000/iron-snout_new.html' },
    { name: 'jelly truck', link: '/100 - 2000/jelly-truck_new.html' },
    { name: 'jet boy', link: '/100 - 2000/jet-boy_new.html' },
    { name: 'jetpack joyride', link: '/100 - 2000/jetpack-joyride_new.html' },
    { name: 'jollyworld', link: '/100 - 2000/jollyworld_new.html' },


    { name: 'jumping shell', link: '/200 - 300/jumping-shell_new.html' },
    { name: 'kart race 3d', link: '/200 - 300/kart-race-3d_new.html' },
    { name: 'kawaii dressup', link: '/200 - 300/kawaii-dressup_new.html' },
    { name: 'kix dream soccer', link: '/200 - 300/kix-dream-soccer_new.html' },
    { name: 'leader strike', link: '/200 - 300/leader-strike_new.html' },
    { name: 'lemonade stand', link: '/200 - 300/lemonade-stand_new.html' },
    { name: 'life the game', link: '/200 - 300/life-the-game_new.html' },
    { name: 'linebacker alley 2', link: '/200 - 300/linebacker-alley-2_new.html' },
    { name: 'ludo multiplayer', link: '/200 - 300/ludo-multiplayer_new.html' },
    { name: 'mad day', link: '/200 - 300/mad-day_new.html' },
    { name: 'mad truck challenge special', link: '/200 - 300/mad-truck-challenge-special_new.html' },
    { name: 'madalin stunt cars 2', link: '/200 - 300/madalin-stunt-cars-2_new.html' },
    { name: 'madalin stunt cars 3', link: '/200 - 300/madalin-stunt-cars-3_new.html' },
    { name: 'marble dash', link: '/200 - 300/marble-dash_new.html' },
    { name: 'masked forces', link: '/200 - 300/masked-forces_new.html' },
    { name: 'master chess', link: '/200 - 300/master-chess_new.html' },
    { name: 'maze path of light', link: '/200 - 300/maze-path-of-light_new.html' },
    { name: 'maze planet 3d', link: '/200 - 300/maze-planet-3d_new.html' },
    { name: 'merge cakes', link: '/200 - 300/merge-cakes_new.html' },
    { name: 'merge cyber racers', link: '/200 - 300/merge-cyber-racers_new.html' },
    { name: 'merge harvest', link: '/200 - 300/merge-harvest_new.html' },
    { name: 'merge round racers', link: '/200 - 300/merge-round-racers_new.html' },
    { name: 'minecraft 1.5.2', link: '/200 - 300/minecraft-1.5.2_new.html' },
    { name: 'minecraft 1.8.8', link: '/200 - 300/minecraft-1.8.8_new.html' },
    { name: 'minecraft builder', link: '/200 - 300/minecraft-builder_new.html' },
    { name: 'minesweeper', link: '/200 - 300/minesweeper_new.html' },
    { name: 'minibattles', link: '/200 - 300/minibattles_new.html' },
    { name: 'mob city', link: '/200 - 300/mob-city_new.html' },
    { name: 'monkey mart', link: '/200 - 300/monkey-mart_new.html' },
    { name: 'monster tracks', link: '/200 - 300/monster-tracks_new.html' },
    { name: 'monsters wheels special', link: '/200 - 300/monsters-wheels-special_new.html' },
    { name: 'mosaic puzzle art', link: '/200 - 300/mosaic-puzzle-art_new.html' },
    { name: 'moto maniac 2', link: '/200 - 300/moto-maniac-2_new.html' },
    { name: 'moto maniac', link: '/200 - 300/moto-maniac_new.html' },
    { name: 'moto road rash 3d', link: '/200 - 300/moto-road-rash-3d_new.html' },
    { name: 'moto trial racing 2', link: '/200 - 300/moto-trial-racing-2_new.html' },
    { name: 'moto x3m 2', link: '/200 - 300/moto-x3m-2_new.html' },
    { name: 'moto x3m pool party', link: '/200 - 300/moto-x3m-pool-party_new.html' },
    { name: 'moto x3m spooky land', link: '/200 - 300/moto-x3m-spooky-land_new.html' },
    { name: 'moto x3m winter', link: '/200 - 300/moto-x3m-winter_new.html' },
    { name: 'moto x3m', link: '/200 - 300/moto-x3m_new.html' },
    { name: 'murder', link: '/200 - 300/murder_new.html' },
    { name: 'my pony my little race', link: '/200 - 300/my-pony-my-little-race_new.html' },
    { name: 'n gon', link: '/200 - 300/n-gon_new.html' },
    { name: 'neon war', link: '/200 - 300/neon-war_new.html' },
    { name: 'noob drive', link: '/200 - 300/noob-drive_new.html' },
    { name: 'offroader v5', link: '/200 - 300/offroader-v5_new.html' },
    { name: 'onion boy', link: '/200 - 300/onion-boy_new.html' },
    { name: 'orbital survival', link: '/200 - 300/orbital-survival_new.html' },
    { name: 'ovo', link: '/200 - 300/ovo_new.html' },
    { name: 'panda bubble shooter', link: '/200 - 300/panda-bubble-shooter_new.html' },
    { name: 'panda simulator 3d', link: '/200 - 300/panda-simulator-3d_new.html' },
    { name: 'paper fighter 3d', link: '/200 - 300/paper-fighter-3d_new.html' },
    { name: 'paper io 2', link: '/200 - 300/paper-io-2_new.html' },
    { name: 'parking fury 2', link: '/200 - 300/parking-fury-2_new.html' },
    { name: 'parking fury 3d bounty hunter', link: '/200 - 300/parking-fury-3d-bounty-hunter_new.html' },
    { name: 'parking fury 3d night thief', link: '/200 - 300/parking-fury-3d-night-thief_new.html' },
    { name: 'parking fury', link: '/200 - 300/parking-fury_new.html' },
    { name: 'parkour block 3d', link: '/200 - 300/parkour-block-3d_new.html' },
    { name: 'penalty kick online', link: '/200 - 300/penalty-kick-online_new.html' },
    { name: 'penalty shooters 2', link: '/200 - 300/penalty-shooters-2_new.html' },
    { name: 'perfect peel', link: '/200 - 300/perfect-peel_new.html' },
    { name: 'ping pong html5', link: '/200 - 300/ping-pong-html5_new.html' },
    { name: 'pixel gun survival', link: '/200 - 300/pixel-gun-survival_new.html' },
    { name: 'pixwars 2', link: '/200 - 300/pixwars-2_new.html' },
    { name: 'plactions', link: '/200 - 300/plactions_new.html' },
    { name: 'pool club', link: '/200 - 300/pool-club_new.html' },
    { name: 'poor bunny', link: '/200 - 300/poor-bunny_new.html' },
    { name: 'pop it master', link: '/200 - 300/pop-it-master_new.html' },
    { name: 'power badminton', link: '/200 - 300/power-badminton_new.html' },
    { name: 'pre civilization bronze age', link: '/200 - 300/pre-civilization-bronze-age_new.html' },
    { name: 'precision client', link: '/200 - 300/precision-client_new.html' },
    { name: 'puppet master', link: '/200 - 300/puppet-master_new.html' },
    { name: 'rabbit samurai', link: '/200 - 300/rabbit-samurai_new.html' },
    { name: 'raft wars 2', link: '/200 - 300/raft-wars-2_new.html' },
    { name: 'raft wars multiplayer', link: '/200 - 300/raft-wars-multiplayer_new.html' },
    { name: 'raft wars', link: '/200 - 300/raft-wars_new.html' },
    { name: 'rally champion', link: '/200 - 300/rally-champion_new.html' },
    { name: 'real cars in city', link: '/200 - 300/real-cars-in-city_new.html' },
    { name: 'real city driving 2', link: '/200 - 300/real-city-driving-2_new.html' },
    { name: 'real simulator monster truck', link: '/200 - 300/real-simulator-monster-truck_new.html' },
    { name: 'recoil', link: '/200 - 300/recoil_new.html' },
    { name: 'red ball 4', link: '/200 - 300/red-ball-4_new.html' },
    { name: 'retro bowl', link: '/200 - 300/retro-bowl_new.html' },
    { name: 'riddle school', link: '/200 - 300/riddle-school_new.html' },
    { name: 'rio rex', link: '/200 - 300/rio-rex_new.html' },
    { name: 'rocket pult', link: '/200 - 300/rocket-pult_new.html' },
    { name: 'rocket soccer derby', link: '/200 - 300/rocket-soccer-derby_new.html' },
    { name: 'rolling sky', link: '/200 - 300/rolling-sky_new.html' },
    { name: 'rolly vortex', link: '/200 - 300/rolly-vortex_new.html' },
    { name: 'roly poly monsters', link: '/200 - 300/roly-poly-monsters_new.html' },
    { name: 'rooftop snipers 2', link: '/200 - 300/rooftop-snipers-2_new.html' },
    { name: 'rooftop snipers', link: '/200 - 300/rooftop-snipers_new.html' },
    { name: 'rowdy city wrestling', link: '/200 - 300/rowdy-city-wrestling_new.html' },
    { name: 'rowdy wrestling', link: '/200 - 300/rowdy-wrestling_new.html' },
    { name: 'run 3 editor', link: '/200 - 300/run-3-editor_new.html' },
    { name: 'running fred', link: '/200 - 300/running-fred_new.html' },
    { name: 'rusher crusher', link: '/200 - 300/rusher-crusher_new.html' },
    { name: 'sausage flip', link: '/200 - 300/sausage-flip_new.html' },
    { name: 'school bus demolition derby', link: '/200 - 300/school-bus-demolition-derby_new.html' },

    { name: 'scrap metal', link: '/300 - 400/scrap-metal_new.html' },
    { name: 'shoot stickman', link: '/300 - 400/shoot-stickman_new.html' },
    { name: 'short life', link: '/300 - 400/short-life_new.html' },
    { name: 'short ride', link: '/300 - 400/short-ride_new.html' },
    { name: 'shortcut race', link: '/300 - 400/shortcut-race_new.html' },
    { name: 'sketchbook 04', link: '/300 - 400/sketchbook-04_new.html' },
    { name: 'skiing fred', link: '/300 - 400/skiing-fred_new.html' },
    { name: 'slime road', link: '/300 - 400/slime-road_new.html' },
    { name: 'slope 2 multiplayer', link: '/300 - 400/slope-2-multiplayer_new.html' },
    { name: 'slope 2', link: '/300 - 400/slope-2_new.html' },
    { name: 'slope 3', link: '/300 - 400/slope-3_new.html' },
    { name: 'slope city', link: '/300 - 400/slope-city_new.html' },
    { name: 'slope tunnel', link: '/300 - 400/slope-tunnel_new.html' },
    { name: 'slope', link: '/300 - 400/slope_new.html' },
    { name: 'smash karts', link: '/300 - 400/smash-karts_new.html' },
    { name: 'sniper gun shooting', link: '/300 - 400/sniper-gun-shooting_new.html' },
    { name: 'snow rider 3d', link: '/300 - 400/snow-rider-3d_new.html' },
    { name: 'soccar', link: '/300 - 400/soccar_new.html' },
    { name: 'soccer random', link: '/300 - 400/soccer-random_new.html' },
    { name: 'soccer skills champions league', link: '/300 - 400/soccer-skills-champions-league_new.html' },
    { name: 'soccer skills euro cup', link: '/300 - 400/soccer-skills-euro-cup_new.html' },
    { name: 'soccer skills world cup', link: '/300 - 400/soccer-skills-world-cup_new.html' },
    { name: 'solitaire', link: '/300 - 400/solitaire_new.html' },
    { name: 'speed boat extreme racing', link: '/300 - 400/speed-boat-extreme-racing_new.html' },
    { name: 'squish run', link: '/300 - 400/squish-run_new.html' },
    { name: 'stack ball', link: '/300 - 400/stack-ball_new.html' },
    { name: 'stack bump 3d', link: '/300 - 400/stack-bump-3d_new.html' },
    { name: 'stack', link: '/300 - 400/stack_new.html' },
    { name: 'stacktris', link: '/300 - 400/stacktris_new.html' },
    { name: 'stair race 3d', link: '/300 - 400/stair-race-3d_new.html' },
    { name: 'stealing the diamond', link: '/300 - 400/stealing-the-diamond_new.html' },
    { name: 'stick defenders', link: '/300 - 400/stick-defenders_new.html' },
    { name: 'stick fighter', link: '/300 - 400/stick-fighter_new.html' },
    { name: 'stick merge', link: '/300 - 400/stick-merge_new.html' },
    { name: 'stickman army team battle', link: '/300 - 400/stickman-army-team-battle_new.html' },
    { name: 'stickman army the resistance', link: '/300 - 400/stickman-army-the-resistance_new.html' },
    { name: 'stickman bike pr', link: '/300 - 400/stickman-bike-pr_new.html' },
    { name: 'stickman bike', link: '/300 - 400/stickman-bike_new.html' },
    { name: 'stickman boxing ko champion', link: '/300 - 400/stickman-boxing-ko-champion_new.html' },
    { name: 'stickman bridge constructor', link: '/300 - 400/stickman-bridge-constructor_new.html' },
    { name: 'stickman climb 2', link: '/300 - 400/stickman-climb-2_new.html' },
    { name: 'stickman fighter epic battle 2', link: '/300 - 400/stickman-fighter-epic-battle-2_new.html' },
    { name: 'stickman fighter mega brawl', link: '/300 - 400/stickman-fighter-mega-brawl_new.html' },
    { name: 'stickman golf', link: '/300 - 400/stickman-golf_new.html' },
    { name: 'stickman hook', link: '/300 - 400/stickman-hook_new.html' },
    { name: 'stickman ragdoll crash fun', link: '/300 - 400/stickman-ragdoll-crash-fun_new.html' },
    { name: 'stickman school run', link: '/300 - 400/stickman-school-run_new.html' },
    { name: 'stock car hero', link: '/300 - 400/stock-car-hero_new.html' },
    { name: 'street ball jam', link: '/300 - 400/street-ball-jam_new.html' },
    { name: 'striker dummies', link: '/300 - 400/striker-dummies_new.html' },
    { name: 'stunt car challenge 3', link: '/300 - 400/stunt-car-challenge-3_new.html' },
    { name: 'stupid zombies', link: '/300 - 400/stupid-zombies_new.html' },
    { name: 'subway runner', link: '/300 - 400/subway-runner_new.html' },
    { name: 'subway surfers beijing', link: '/300 - 400/subway-surfers-beijing_new.html' },
    { name: 'subway surfers houston', link: '/300 - 400/subway-surfers-houston_new.html' },
    { name: 'subway surfers monaco', link: '/300 - 400/subway-surfers-monaco_new.html' },
    { name: 'subway surfers newyork', link: '/300 - 400/subway-surfers-newyork_new.html' },
    { name: 'subway surfers', link: '/300 - 400/subway-surfers_new.html' },
    { name: 'super bike the champion', link: '/300 - 400/super-bike-the-champion_new.html' },
    { name: 'super hexbee merger', link: '/300 - 400/super-hexbee-merger_new.html' },
    { name: 'super hot', link: '/300 - 400/super-hot_new.html' },
    { name: 'super liquid soccer', link: '/300 - 400/super-liquid-soccer_new.html' },
    { name: 'super mario 64', link: '/300 - 400/super-mario-64_new.html' },
    { name: 'super mario bros', link: '/300 - 400/super-mario-bros_new.html' },
    { name: 'super racing gt drag pro', link: '/300 - 400/super-racing-gt-drag-pro_new.html' },
    { name: 'super santa kicker', link: '/300 - 400/super-santa-kicker_new.html' },
    { name: 'super star car', link: '/300 - 400/super-star-car_new.html' },
    { name: 'super tunnel rush', link: '/300 - 400/super-tunnel-rush_new.html' },
    { name: 'superbattle 2', link: '/300 - 400/superbattle-2_new.html' },
    { name: 'superbike hero', link: '/300 - 400/superbike-hero_new.html' },
    { name: 'survivor in rainbow monster', link: '/300 - 400/survivor-in-rainbow-monster_new.html' },
    { name: 'swatforce vs terrorists', link: '/300 - 400/swatforce-vs-terrorists_new.html' },
    { name: 'swingo', link: '/300 - 400/swingo_new.html' },
    { name: 'tag', link: '/300 - 400/tag_new.html' },
    { name: 'tank trouble 2', link: '/300 - 400/tank-trouble-2_new.html' },
    { name: 'tanuki sunset', link: '/300 - 400/tanuki-sunset_new.html' },
    { name: 'temple of boom', link: '/300 - 400/temple-of-boom_new.html' },
    { name: 'temple run 2', link: '/300 - 400/temple-run-2_new.html' },
    { name: 'tennis masters', link: '/300 - 400/tennis-masters_new.html' },
    { name: 'terris', link: '/300 - 400/terris_new.html' },
    { name: 'tetris flash', link: '/300 - 400/tetris-flash_new.html' },
    { name: 'the impossible quiz', link: '/300 - 400/the-impossible-quiz_new.html' },
    { name: 'the little giant', link: '/300 - 400/the-little-giant_new.html' },
    { name: 'the spear stickman', link: '/300 - 400/the-spear-stickman_new.html' },
    { name: 'there is no game', link: '/300 - 400/there-is-no-game_new.html' },
    { name: 'three goblets', link: '/300 - 400/three-goblets_new.html' },
    { name: 'thumb fighter christmas', link: '/300 - 400/thumb-fighter-christmas_new.html' },
    { name: 'thumb fighter', link: '/300 - 400/thumb-fighter_new.html' },
    { name: 'tictactoe', link: '/300 - 400/tictactoe_new.html' },
    { name: 'tiger simulator 3d', link: '/300 - 400/tiger-simulator-3d_new.html' },
    { name: 'tiny fishing', link: '/300 - 400/tiny-fishing_new.html' },
    { name: 'tinytownracing', link: '/300 - 400/tinytownracing_new.html' },
    { name: 'tomb of the mask color', link: '/300 - 400/tomb-of-the-mask-color_new.html' },
    { name: 'tomb of the mask', link: '/300 - 400/tomb-of-the-mask_new.html' },
    { name: 'toon off', link: '/300 - 400/toon-off_new.html' },
    { name: 'top speed 3d', link: '/300 - 400/top-speed-3d_new.html' },
    { name: 'top speed racing 3d', link: '/300 - 400/top-speed-racing-3d_new.html' },
    { name: 'tower of destiny', link: '/300 - 400/tower-of-destiny_new.html' },
    { name: 'traffic mania', link: '/300 - 400/traffic-mania_new.html' },
    { name: 'traffic rider', link: '/300 - 400/traffic-rider_new.html' },

    { name: 'tricks', link: '/400 - 429/tricks_new.html' },
    { name: 'truck traffic', link: '/400 - 429/truck-traffic_new.html' },
    { name: 'tube jumpers', link: '/400 - 429/tube-jumpers_new.html' },
    { name: 'tunnel rush', link: '/400 - 429/tunnel-rush_new.html' },
    { name: 'turbo moto racer', link: '/400 - 429/turbo-moto-racer_new.html' },
    { name: 'two ball 3d dark', link: '/400 - 429/two-ball-3d-dark_new.html' },
    { name: 'two neon boxes', link: '/400 - 429/two-neon-boxes_new.html' },
    { name: 'ultimate car driving', link: '/400 - 429/ultimate-car-driving_new.html' },
    { name: 'unicycle hero', link: '/400 - 429/unicycle-hero_new.html' },
    { name: 'vex 4', link: '/400 - 429/vex-4_new.html' },
    { name: 'vex 5', link: '/400 - 429/vex-5_new.html' },
    { name: 'vex 6', link: '/400 - 429/vex-6_new.html' },
    { name: 'vex 7', link: '/400 - 429/vex-7_new.html' },
    { name: 'volley random', link: '/400 - 429/volley-random_new.html' },
    { name: 'volleyball challenge', link: '/400 - 429/volleyball-challenge_new.html' },
    { name: 'water color sort', link: '/400 - 429/water-color-sort_new.html' },
    { name: 'we become what we behold', link: '/400 - 429/we-become-what-we-behold_new.html' },
    { name: 'where is my cat', link: '/400 - 429/where-is-my-cat_new.html' },
    { name: 'who is', link: '/400 - 429/who-is_new.html' },
    { name: 'wizard mike', link: '/400 - 429/wizard-mike_new.html' },
    { name: 'wood blocks 3d', link: '/400 - 429/wood-blocks-3d_new.html' },
    { name: 'word city crossed', link: '/400 - 429/word-city-crossed_new.html' },
    { name: 'word city uncrossed', link: '/400 - 429/word-city-uncrossed_new.html' },
    { name: 'wordle unlimited', link: '/400 - 429/wordle-unlimited_new.html' },
    { name: 'words search classic edition', link: '/400 - 429/words-search-classic-edition_new.html' },
    { name: 'worlds hardest game 2', link: '/400 - 429/worlds-hardest-game-2_new.html' },
    { name: 'worlds hardest game 3', link: '/400 - 429/worlds-hardest-game-3_new.html' },
    { name: 'wrassling', link: '/400 - 429/wrassling_new.html' },
    { name: 'zombie derby pixel survival', link: '/400 - 429/zombie-derby-pixel-survival_new.html' },

    { name: 'snake', link: '/faveret/snake.html' },
    { name: 'snowball io', link: '/faveret/Snowball_io.html' },
    { name: 'time shooter 3 SWAT', link: '/faveret/Time_Shooter_3_SWAT.html' },

    { name: '1v1-lol-offline', link: '/game-new1/1v1-lol-offline_new.html' },
    { name: '2-minute-football', link: '/game-new1/2-minute-football_new.html' },
    { name: '3d-monster-truck-skyroads', link: '/game-new1/3d-monster-truck-skyroads_new.html' },
    { name: 'archer-master-3d-castle-defense', link: '/game-new1/archer-master-3d-castle-defense_new.html' },
    { name: 'avalanche', link: '/game-new1/avalanche_new.html' },
    { name: 'bacon-may-die', link: '/game-new1/bacon-may-die_new.html' },
    { name: 'basketball-frvr', link: '/game-new1/basketball-frvr_new.html' },
    { name: 'battle-golf', link: '/game-new1/battle-golf_new.html' },
    { name: 'blobby-clicker', link: '/game-new1/blobby-clicker_new.html' },
    { name: 'blumgi-dragon', link: '/game-new1/blumgi-dragon_new.html' },
    { name: 'bouncy-basketball', link: '/game-new1/bouncy-basketball_new.html' },
    { name: 'boxrob-3', link: '/game-new1/boxrob-3_new.html' },
    { name: 'boxrob-2', link: '/game-new1/boxrob-2_new.html' },
    { name: 'boxrob', link: '/game-new1/boxrob_new.html' },
    { name: 'bubbles-cool', link: '/game-new1/bubbles-cool_new.html' },
    { name: 'burnout-extreme-drift-2', link: '/game-new1/burnout-extreme-drift-2_new.html' },
    { name: 'car-drift-racers-2', link: '/game-new1/car-drift-racers-2_new.html' },
    { name: 'car-eats-car-winter-adventure', link: '/game-new1/car-eats-car-winter-adventure_new.html' },
    { name: 'car-simulator-arena', link: '/game-new1/car-simulator-arena_new.html' },
    { name: 'catpad', link: '/game-new1/catpad_new.html' },
    { name: 'colorup', link: '/game-new1/colorup_new.html' },
    { name: 'cow-bay', link: '/game-new1/cow-bay_new.html' },
    { name: 'cozy-room-design', link: '/game-new1/cozy-room-design_new.html' },
    { name: 'craftomation-1', link: '/game-new1/craftomation-1_new.html' },
    { name: 'dark-runner', link: '/game-new1/dark-runner_new.html' },
    { name: 'descent', link: '/game-new1/descent_new.html' },
    { name: 'detective-dan', link: '/game-new1/detective-dan_new.html' },
    { name: 'dino-bros', link: '/game-new1/dino-bros_new.html' },
    { name: 'double-panda', link: '/game-new1/double-panda_new.html' },
    { name: 'dragon-simulator-3d', link: '/game-new1/dragon-simulator-3d_new.html' },
    { name: 'dubai-police-parking-2', link: '/game-new1/dubai-police-parking-2_new.html' },
    { name: 'dunk-perfect', link: '/game-new1/dunk-perfect_new.html' },
    { name: 'duo-survival-2', link: '/game-new1/duo-survival-2_new.html' },
    { name: 'duo-survival-3', link: '/game-new1/duo-survival-3_new.html' },
    { name: 'duo-survival', link: '/game-new1/duo-survival_new.html' },
    { name: 'duo-vikings-2', link: '/game-new1/duo-vikings-2_new.html' },
    { name: 'duo-vikings-3', link: '/game-new1/duo-vikings-3_new.html' },
    { name: 'duo-vikings', link: '/game-new1/duo-vikings_new.html' },
    { name: 'element-blocks', link: '/game-new1/element-blocks_new.html' },
    { name: 'extreme-off-road-cars-3-cargo', link: '/game-new1/extreme-off-road-cars-3-cargo_new.html' },
    { name: 'extreme-off-road-cars', link: '/game-new1/extreme-off-road-cars_new.html' },
    { name: 'fireboy-and-watergirl-1-forest-temple', link: '/game-new1/fireboy-and-watergirl-1-forest-temple_new.html' },
    { name: 'fireboy-and-watergirl-2-light-temple', link: '/game-new1/fireboy-and-watergirl-2-light-temple_new.html' },
    { name: 'fireboy-and-watergirl-4-crystal-temple', link: '/game-new1/fireboy-and-watergirl-4-crystal-temple_new.html' },
    { name: 'fireboy-and-watergirl-5-elements', link: '/game-new1/fireboy-and-watergirl-5-elements_new.html' },
    { name: 'fireboy-watergirl-3-ice-temple', link: '/game-new1/fireboy-watergirl-3-ice-temple_new.html' },
    { name: 'fireboy-watergirl-6-fairy-tales', link: '/game-new1/fireboy-watergirl-6-fairy-tales_new.html' },
    { name: 'flip-bros', link: '/game-new1/flip-bros_new.html' },
    { name: 'flip-runner', link: '/game-new1/flip-runner_new.html' },
    { name: 'fnf-b-sides', link: '/game-new1/fnf-b-sides_new.html' },
    { name: 'fnf-hatsune-miku', link: '/game-new1/fnf-hatsune-miku_new.html' },
    { name: 'fnf-shaggy-matt', link: '/game-new1/fnf-shaggy-matt_new.html' },
    { name: 'fnf-week-7', link: '/game-new1/fnf-week-7_new.html' },
    { name: 'fnf-xe', link: '/game-new1/fnf-xe_new.html' },
    { name: 'football-blitz', link: '/game-new1/football-blitz_new.html' },
    { name: 'fortride-open-world', link: '/game-new1/fortride-open-world_new.html' },
    { name: 'four-in-a-row', link: '/game-new1/four-in-a-row_new.html' },
    { name: 'fox-simulator-3d', link: '/game-new1/fox-simulator-3d_new.html' },
    { name: 'fury-wars', link: '/game-new1/fury-wars_new.html' },
    { name: 'g-switch-4', link: '/game-new1/g-switch-4_new.html' },
    { name: 'hide-and-smash', link: '/game-new1/hide-and-smash_new.html' },
    { name: 'highway-bike-simulator', link: '/game-new1/highway-bike-simulator_new.html' },
    { name: 'hills-of-steel', link: '/game-new1/hills-of-steel_new.html' },
    { name: 'hypersnake', link: '/game-new1/hypersnake_new.html' },
    { name: 'idle-zoo-safari-rescue', link: '/game-new1/idle-zoo-safari-rescue_new.html' },
    { name: 'izowave-build-and-defend', link: '/game-new1/izowave-build-and-defend_new.html' },
    { name: 'james-gun', link: '/game-new1/james-gun_new.html' },
    { name: 'just-park-it-11', link: '/game-new1/just-park-it-11_new.html' },
    { name: 'just-park-it-12', link: '/game-new1/just-park-it-12_new.html' },
    { name: 'kart-wars', link: '/game-new1/kart-wars_new.html' },
    { name: 'lands-of-blight', link: '/game-new1/lands-of-blight_new.html' },
    { name: 'level-devil', link: '/game-new1/level-devil_new.html' },
    { name: 'little-master-cricket', link: '/game-new1/little-master-cricket_new.html' },
    { name: 'lurkers-io', link: '/game-new1/lurkers-io_new.html' },
    { name: 'make-it-meme', link: '/game-new1/make-it-meme_new.html' },
    { name: 'merge-party', link: '/game-new1/merge-party_new.html' },
    { name: 'misland', link: '/game-new1/misland_new.html' },
    { name: 'monster-truck-racing-arena', link: '/game-new1/monster-truck-racing-arena_new.html' },
    { name: 'moto-space-racing-2-player', link: '/game-new1/moto-space-racing-2-player_new.html' },
    { name: 'moving-truck-bounty', link: '/game-new1/moving-truck-bounty_new.html' },
    { name: 'mystical-birdlink', link: '/game-new1/mystical-birdlink_new.html' },
    { name: 'narrow-one', link: '/game-new1/narrow-one_new.html' },
    { name: 'noob-hook', link: '/game-new1/noob-hook_new.html' },
    { name: 'odd-bot-out', link: '/game-new1/odd-bot-out_new.html' },
    { name: 'off-road-rain-cargo-simulator', link: '/game-new1/off-road-rain-cargo-simulator_new.html' },
    { name: 'orange', link: '/game-new1/orange_new.html' },
    { name: 'pack-a-bag', link: '/game-new1/pack-a-bag_new.html' },
    { name: 'paper-minecraft', link: '/game-new1/paper-minecraft_new.html' },
    { name: 'parking-fury-3d-beach-city', link: '/game-new1/parking-fury-3d-beach-city_new.html' },
    { name: 'parking-fury-3d', link: '/game-new1/parking-fury-3d_new.html' },
    { name: 'parkmania', link: '/game-new1/parkmania_new.html' },
    { name: 'parkour-race', link: '/game-new1/parkour-race_new.html' },
    { name: 'partytoons', link: '/game-new1/partytoons_new.html' },
    { name: 'peppa-pig-basketball', link: '/game-new1/peppa-pig-basketball_new.html' },
    { name: 'perfect-dunk', link: '/game-new1/perfect-dunk_new.html' },
    { name: 'rainbow-obby', link: '/game-new1/rainbow-obby_new.html' },
    { name: 'retro-highway', link: '/game-new1/retro-highway_new.html' },
    { name: 'rugby-rush', link: '/game-new1/rugby-rush_new.html' },
    { name: 'runman-race-around-the-world', link: '/game-new1/runman-race-around-the-world_new.html' },
    { name: 'scrap-divers', link: '/game-new1/scrap-divers_new.html' },
    { name: 'shady-bears', link: '/game-new1/shady-bears_new.html' },
    { name: 'shape-fold-animals', link: '/game-new1/shape-fold-animals_new.html' },
    { name: 'shape-fold-html5', link: '/game-new1/shape-fold-html5_new.html' },
    { name: 'shape-fold-nature', link: '/game-new1/shape-fold-nature_new.html' },
    { name: 'sharkio', link: '/game-new1/sharkio_new.html' },
    { name: 'shootz', link: '/game-new1/shootz_new.html' },
    { name: 'skibidi-shooter', link: '/game-new1/skibidi-shooter_new.html' },
    { name: 'slalom-hero', link: '/game-new1/slalom-hero_new.html' },
    { name: 'slime-laboratory', link: '/game-new1/slime-laboratory_new.html' },
    { name: 'sling-drift', link: '/game-new1/sling-drift_new.html' },
    { name: 'slope-tunnel', link: '/game-new1/slope-tunnel_new.html' },
    { name: 'slopey', link: '/game-new1/slopey_new.html' },
    { name: 'slot-car-racing', link: '/game-new1/slot-car-racing_new.html' },
    { name: 'snail-bob-6', link: '/game-new1/snail-bob-6_new.html' },
    { name: 'snake-is-mlg-edition', link: '/game-new1/snake-is-mlg-edition_new.html' },
    { name: 'stickman-crazy-box', link: '/game-new1/stickman-crazy-box_new.html' },
    { name: 'stickman-fight-ragdoll', link: '/game-new1/stickman-fight-ragdoll_new.html' },
    { name: 'super-mx-the-champion', link: '/game-new1/super-mx-the-champion_new.html' },
    { name: 'superbrawl', link: '/game-new1/superbrawl_new.html' },
    { name: 'supernova', link: '/game-new1/supernova_new.html' },
    { name: 'tag-2', link: '/game-new1/tag-2_new.html' },
    { name: 'tetra-blocks', link: '/game-new1/tetra-blocks_new.html' },
    { name: 'tetris-99', link: '/game-new1/tetris-99_new.html' },
    { name: 'tetris', link: '/game-new1/tetris_new.html' },
    { name: 'throw-it-higher', link: '/game-new1/throw-it-higher_new.html' },
    { name: 'touchdowners', link: '/game-new1/touchdowners_new.html' },
    { name: 'traffic-escape', link: '/game-new1/traffic-escape_new.html' },
    { name: 'traffic-rush', link: '/game-new1/traffic-rush_new.html' },
    { name: 'truck-loader-2', link: '/game-new1/truck-loader-2_new.html' },
    { name: 'truck-loader-3', link: '/game-new1/truck-loader-3_new.html' },
    { name: 'truck-loader-4', link: '/game-new1/truck-loader-4_new.html' },
    { name: 'truck-loader-5', link: '/game-new1/truck-loader-5_new.html' },
    { name: 'truck-loader', link: '/game-new1/truck-loader_new.html' },
    { name: 'two-button-bounce', link: '/game-new1/two-button-bounce_new.html' },
    { name: 'vectaria-io', link: '/game-new1/vectaria-io_new.html' },
    { name: 'village-craft', link: '/game-new1/village-craft_new.html' },
    { name: 'war-of-caribbean-pirates', link: '/game-new1/war-of-caribbean-pirates_new.html' },
    { name: 'yohoho-io', link: '/game-new1/yohoho-io_new.html' },
    { name: 'zeepkist-crash-2d', link: '/game-new1/zeepkist-crash-2d_new.html' },
    { name: 'zombie-siege-outbreak', link: '/game-new1/zombie-siege-outbreak_new.html' },
    { name: 'zombotag', link: '/game-new1/zombotag_new.html' },
    { name: 'zoom-be-2', link: '/game-new1/zoom-be-2_new.html' },
    { name: 'zoom-be-3', link: '/game-new1/zoom-be-3_new.html' },
    { name: 'zoom-be', link: '/game-new1/zoom-be_new.html' },

    ];
}
function performSearch() {
    var searchQuery = document.getElementById('search').value.toLowerCase();
    var fileLinks = games();
    var searchResultsDiv = document.getElementById('searchResults');
    searchResultsDiv.innerHTML = ""; 

    for (var i = 0; i < fileLinks.length; i++) {
        var fileName = fileLinks[i].name.toLowerCase();

        if (fileName.includes(searchQuery)) {
          var resultItem = document.createElement('a');
          resultItem.textContent = fileLinks[i].name;
          resultItem.href = fileLinks[i].link;
          searchResultsDiv.appendChild(resultItem);
        }
    }
}
function openq() {
  document.getElementById("Quickaccess").style.width = "250px";
}
function closeq() {
  document.getElementById("Quickaccess").style.width = "0";
}
var currentPage = window.location.pathname;
var visitedPages = JSON.parse(localStorage.getItem('visitedPages')) || [];
var pageIndex = visitedPages.indexOf(currentPage);
if (pageIndex !== -1) {
  visitedPages.splice(pageIndex, 1);
}
visitedPages.unshift(currentPage);
localStorage.setItem('visitedPages', JSON.stringify(visitedPages));


function gra(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'none';
  darkb.style.display = 'block';
  lightb.style.display = 'none';
  bodyElement.classList = [];
  bodyElement.classList.add("gra");
  window.sessionStorage.background = "gra";
}
function dark(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'none';
  darkb.style.display = 'none';
  lightb.style.display = 'block';
  bodyElement.classList = [];
  bodyElement.classList.add("dark");
  window.sessionStorage.background = "dark";
}
function light(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'block';
  darkb.style.display = 'none';
  lightb.style.display = 'none';
  bodyElement.classList = [];
  bodyElement.classList.add("light");
  window.sessionStorage.background = "light";
}
if (window.sessionStorage.background == "gra"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("gra");
}else if (window.sessionStorage.background == "light"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("light");
}else if (window.sessionStorage.background == "dark"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("dark");
}else{
  var bodyElement = document.body;
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  bodyElement.classList.add("gra");
  window.sessionStorage.background = "gra";
}
